name: Deploy to Netlify on index.html Change

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'projects.json'
      - 'script.js'
      - 'style.css'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Deployment
        run: |
          curl -X POST "${{ secrets.NETLIFY_BUILD_HOOK}}"
